### ISSUE TITLE
Integrate with PlaceHolder.it

### ISSUE THREAD

**Issue by jacquescrocker** [trvsdnn/frank#13]
awesome service: http://www.placehold.it/

Matt Darby wrote a nice little gem wrapper aound it already:
http://www.protectedmethod.com/blog/4c5de08d9fad1f229e000008/www.placehold.it

allows us to remove minimagick stuff

**Comment by trvsdnn** [comment]
I've been thinking about moving the lorem image stuff to placehold.it. ImageMagick is a big dependency... I am a little partial to the duck images, but yeah lets move it over to placehold.

 I'd rather not have a gem dependency though. That entire service can be wrapped up in a single helper, and i'd like to add random color support, so i'll work on that.

**Comment by jacquescrocker** [comment]
cool. yeah, i agree on avoiding the gem dependency. its way too simple. maybe we can steal some of his code though :-)

**Comment by trvsdnn** [comment]
Done in 0.4.x
