### ISSUE TITLE
Remove mongrel dependency?

### ISSUE THREAD

**Issue by jacquescrocker** [trvsdnn/frank#14]

**Comment by jacquescrocker** [comment]
I tried installing my static site app on one of my designer's computers and it didnt go well :-). Basically he didn't have XCode installed, and Mongrel gem install blows up without it. 

We should probably just remove it as a gem dependency and default to webrick if mongrel isnt available

**Comment by trvsdnn** [comment]
Yeah, that's fine with me.

**Comment by jacquescrocker** [comment]
Fixed via
http://github.com/blahed/frank/commit/d554b13f5521cf85385dfa65e8f5f29a87ba9a48

To help newbies get started who generate a project but dont have mongrel installed, it will always fall back to webrick if the configured server handler is not available. 

I left mongrel as the default in the generated apps since I think its still the nicest local server to work with.
