### ISSUE TITLE
Add CoffeeScript Support

### ISSUE THREAD

**Issue by jacquescrocker** [trvsdnn/frank#16]
josh peek put together a nice ruby library that wraps around coffee-script (node). Should make it really easy to add proper coffeescript support to Frank 
http://rubygems.org/gems/coffee-script

Depending on how hard this is, I'll try to get this in as a 0.4 patch. If its too hard, i'll push to 0.5.

**Comment by trvsdnn** [comment]
I think, coffeescript just got readded to tilt... i'll have to check into that though.

**Comment by jacquescrocker** [comment]
oh hey... yeah. http://twitter.com/rtomayko/statuses/24131951744

Very cool. maybe tilt 1.1 is the way to go

**Comment by leondewey** [comment]
Dose frank play nice with coffee now? if so how do you get it to work?

**Comment by trvsdnn** [comment]
Haven't added this feature back yet... mainly because node is a pretty big dependency. I'll see if I can figure something out in the next couple of days.

**Comment by jacquescrocker** [comment]
`coffee-script` gem now uses therubyracer to compile everything (no node needed)
https://rubygems.org/gems/coffee-script

I think the latest tilt uses the coffee-script gem, so if we get on the latest version, it should be possible out of the box

**Comment by trvsdnn** [comment]
rawk... i'll check it out tonight

**Comment by leondewey** [comment]
Thanks! I had a little go at it when generate runs it compiles the coffee but the it gets a layout added to it.

**Comment by trvsdnn** [comment]
Just released 1.0.4. It should be working.

**Comment by leondewey** [comment]
Hey thanks! just about to check it out now

**Comment by leondewey** [comment]
Works really good thanks!

**Comment by trvsdnn** [comment]
Nice.
