### ISSUE TITLE
SCSS @import load_path error

### ISSUE THREAD

**Issue by wyattdanger** [trvsdnn/frank#20]
When attempting to use the @import directive in a SCSS file, the file to be compiled is not found, and a traditional CSS @import is written. This trace can be thrown http://cl.ly/8cb11c7b3342b16d5f03

This is the feature I'm trying to use: http://markup.io/v/r99g0hts2snd

**Comment by trvsdnn** [comment]
You can set the sass load_paths in setup.rb with something like this:

```
Frank.sass_options = { :load_paths => [ File.join(File.dirname(__FILE__), 'dynamic/stylesheets') ] }
```

**Comment by wyattdanger** [comment]
Word! Works beautifully.
