### ISSUE TITLE
sitemap.xml on 'frank export --production' ?

### ISSUE THREAD

**Issue by wyattdanger** [trvsdnn/frank#27]
Not an issue but a suggestion. Perhaps frank export with a production switch can generate a sitemap.xml file?

**Comment by trvsdnn** [comment]
I've considered this one a few times... Maybe something like a --with-sitemap argument?

**Comment by trvsdnn** [comment]
Seems like this could be useful as a special route that would show a tree structure of your site's pages? Possibly with an option to export the tree as a sitemap?

Any thoughts?

**Comment by wyattdanger** [comment]
It'd be nice to have XML and HTML versions, each accessible by helper functions
