### ISSUE TITLE
Ability to pass HAML config variables

### ISSUE THREAD

**Issue by wyattdanger** [trvsdnn/frank#32]
I can pass Sass options with the sass_options method but can not figure out how to pass Haml options. I tried adding this at the bottom of settings.rb

```
require 'haml'
require 'haml/template'
Haml::Template.options = { :format => :html4 }
```

This is not currently working, and will throw an error without the second line or without the third line.

**Comment by trvsdnn** [comment]
Added support for `Frank.haml_options`. It's in the new release 1.0.8.

`gem install frank`

Then just add a line to setup.rb:

`Frank.haml_options = { :format => :html4, :ugly => true }`

**Comment by wyattdanger** [comment]
Awesome! Thank you, sir.
