### ISSUE TITLE
template directory is in LOAD_PATH

### ISSUE THREAD

**Issue by ghost** [trvsdnn/frank#5]
Do not put template/ in lib directory. Big NO NO.

**Comment by trvsdnn** [comment]
Why? Seems like a fairly common approach.

**Comment by ghost** [comment]
Unfortunately bad solutions can propagate as easily as good ones when people are learning how to do things.

Read: http://wiki.github.com/proutils/pom/project-standards

Basically you are claiming an ownership of the name "template" by using it in lib/. Consider what happens if someone else decided to call their project "template" --perhaps an odd name for a project but stranger things have happened.

**Comment by jacquescrocker** [comment]
since this is a framework, it should be ok. i tried moving template/ into lib but it broke everything. closing, however we'll accept a patch for 0.4 if you submit!
