### ISSUE TITLE
ERROR SystemExit: exit - Frank Does not exit correctly

### ISSUE THREAD

**Issue by 0xO0O0** [trvsdnn/frank#51]
When ever I hit ctl + c to exit the frank server I receive this message  ERROR SystemExit: exit
/Users/iam/.rvm/gems/ruby-1.9.2-p180/gems/frank-1.0.8/lib/frank/base.rb:298:in `exit'

**Comment by 0xO0O0** [comment]
my fault not yours, i was trying to use unicorn, even though it is a rack server, it does not work with this gem :(

**Comment by trvsdnn** [comment]
I'll do some research into this... haven't played with unicorn yet, and this seems like a good reason to.

**Comment by 0xO0O0** [comment]
thanks a lot, i must say that I love the frank gem, please keep up the great work
