### ISSUE TITLE
Concept of development vs production environment?

### ISSUE THREAD

**Issue by fleetio** [trvsdnn/frank#58]
Is there a good way to differentiate between a development & production environment? Some things, like analytics tracking scripts, I don't want to render in development but I do want them to render when actually exporting the site.

I know there's a `--production` flag that can be used when exporting. Any way to hook into that and do something like this in a view?

```
- if Frank.production?
  -# only renders when exporting site
```

**Comment by trvsdnn** [comment]
You can use `Frank.exporting?` in a template which will be true if you are exporting or compiling the project and false whenever you are running the dev server.

`Frank.production?` is sort of a different thing. I do need to rethink and maybe rename a few of those methods to reduce confusion, but for now you can use `Frank.exporting?`.

**Comment by fleetio** [comment]
Oh cool - I didn't realize that was an option. Exactly what I need. Thanks!

**Comment by edrex** [comment]
kinda figured it was a documentation issue :)

Added a [FAQs page](https://github.com/blahed/frank/wiki/FAQs)
