### ISSUE TITLE
exporting? etc from templates

### ISSUE THREAD

**Issue by edrex** [trvsdnn/frank#60]
I need a hack like 

``` haml
- if Frank::Setting.exporting?
  %link{:charset => "utf-8", :href => "/css/cloudfeet.css", :rel => "stylesheet", :type => "text/css"}
- else
  %link{:charset => "utf-8", :href => "/less/cloudfeet.less", :rel => "stylesheet/less", :type => "text/css"}
  %script{:type => "text/javascript", :src => "/js/less.js"}
```

to work around the less gem segfaulting ( not frank's fault, obviously :).

But it seems I don't have access to Setting from templates:

```
The error, « uninitialized constant Frank::Setting »
occurred
```

It seems like it would be generally useful to be able to find out what mode we're in from the templates. What's the simplest way to do this?

Thanks :)

**Comment by trvsdnn** [comment]
Check this https://github.com/blahed/frank/issues/58 ;)

Hopefully that fixes it?
