### ISSUE TITLE
Frank creating /* Line ... */ in my CSS Files

### ISSUE THREAD

**Issue by alenm** [trvsdnn/frank#61]
When I decide to 'frank export',  my CSS file is littered with so many CSS Comments that outlines with the line number is in my SASS file. How can I prevent it from happening?

/\* line 1, /Users/Mac/Dev/blog/dynamic/css/common.sass */
# header {

  text-align: center;
  height: 80px;
  font-family: "Arial";
  padding-top: 20px;
}

**Comment by trvsdnn** [comment]
I can't imagine how frank would be doing this. Have you tried upgrade to the latest tilt and sass?

**Comment by alenm** [comment]
I just tried updating my gems. I have 
sass (3.1.10, 3.1.7)
tilt (1.3.3)
frank (1.0.9)
OS X 10.7.2
ruby 1.9.2p290

**Comment by trvsdnn** [comment]
It's a sass config option. http://wiseheartdesign.com/articles/2010/01/21/better-debugging-with-sass-and-line-comments/

**Comment by alenm** [comment]
Looks like it is, thanks for the quick find
