### ISSUE TITLE
Refreshing causes 404's

### ISSUE THREAD

**Issue by btelles** [trvsdnn/frank#65]
When using Firefox (not sure if this has anything to do with it) I get 404's on seemingly random js files.

typing in the full url for the page (http://localhost:3601) gets all the js to show up, but as soon as I try to refresh the 404's start coming up.

Has anyone else encountered this?

**Comment by fleetio** [comment]
I'm getting the same thing in Chrome. Not sure why. Everything used to work perfectly, but now I get 404s all the time... Ever figure anything out?

**Comment by fleetio** [comment]
Figured it out. There must be some issues with the latest version of Rack because I specified an older version in my Gemfile and we're all good once again.

#### Gemfile:

``` ruby
source "http://rubygems.org"

gem "thin", "~> 1.3.1"

group :development do
  gem "rack", "~> 1.3.5"
  gem "frank", "~> 1.0.9"
  gem "haml", "~> 3.1.4"
  gem "less", "~> 2.0.8"
  gem "coffee-script", "~> 2.2.0"
end
```

#### Then run:

```
bundle install
```

#### And be sure to use `bundle exec` when starting the Frank server:

```
bundle exec frank server
```

**Comment by wyattdanger** [comment]
+1, I've been getting lots of 404s for both JavaScript files and images. Started about a month ago.

**Comment by Dahie** [comment]
I experience the same problems using rack 1.4.1.

**Comment by defsprite** [comment]
The 404 issue is fixed in master, but not released yet.

**Comment by trvsdnn** [comment]
1.0.10 just released

**Comment by Dahie** [comment]
Thank you, works fine.
