### ISSUE TITLE
Sitewide variables?

### ISSUE THREAD

**Issue by casey-chow** [trvsdnn/frank#66]
I saw that `Frank.exporting?` can be used sitewide throughout all the layouts, etc. 

Are there any plans to allow us to do similar sitewide variables? Is it already implemented?

**Comment by trvsdnn** [comment]
You can use meta data for template specific variables:

```
    foo: bar
    --------------------------META

    <%= foo %>
```

You can use helpers for methods that you want to use in all the templates/layouts. I am planning on restructuring this to make it cleaner and easier in the next release.
