### ISSUE TITLE
Determining if in production mode in setup.rb

### ISSUE THREAD

**Issue by manuelmeurer** [trvsdnn/frank#68]
I am trying to set the Compass http_path to a CDN in production mode. Unfortunately `Frank::Settings.instance.production?` still returns false at this point since the setup.rb is parsed before the settings are set.
I tried to refactor it to set the settings before parsing setup.rb but ran into other problems on the way.
Now I am using `Frank::CLI.instance_variable_get('@options')[:production]` in setup.rb which feels like punching a puppy every time I deploy.
Is there a better way to do it?

**Comment by trvsdnn** [comment]
Hadn't thought about this as being a need, looks like it is. I can't think of a better way to handle it right now, but I'll make it part of the next major release for sure.

**Comment by manuelmeurer** [comment]
Great, thanks a lot!
