### ISSUE TITLE
content_for

### ISSUE THREAD

**Issue by cullepm3** [trvsdnn/frank#69]
Is content_for supported?  I tried to use, but it didn't work, the body part was inserted twice.  

Eg. 

```
%h3
  =yield :title

=yield

-----
- content_for :title do  
  ="News - updated Feb 27th 2012"

Blah Blah Blah
```

returns

```
<h3>Blah Blah Blah<h3>
Blah Blah Blah
```

**Comment by trvsdnn** [comment]
It is supported, but you don't use `yield` to get the content in the layout. You call content_for with the symbol that you used in the template.

```
=content_for :title
# instead of
=yield :title
```
