### ISSUE TITLE
Compass support?

### ISSUE THREAD

**Issue by jacquescrocker** [trvsdnn/frank#7]
Trying to figure out how to attach compass to Frank. Any docs on this? Would be cool if we could simplify it for new users a bit.

compass-style.org/

Thanks!

**Comment by jacquescrocker** [comment]
Basically I just need an initializer hook and I'll be set. Digging through the source code, I should be able to find the right spot. Here's what I need to add to load the right compass stuff:

```
require 'compass'

Compass.configuration do |config|

  config.project_path = File.dirname(__FILE__)

  config.sass_dir = File.join(‘src’, ‘stylesheets’ )

end
```

Then I just need to set sass_options (on tilt), and it'll be good to go!

```
# the ghetto monkey patch approach...
class Tilt::SassTemplate
  def options
     Compass.sass_engine_options
  end
end
```

**Comment by trvsdnn** [comment]
I haven't messed with compass much, it seems very promising though. I'd like to figure out an elegant way to support it out of the box. I'll need some time to research and look around, but if you figure something out, i'd be happy to pull it in.

**Comment by jacquescrocker** [comment]
Cool, I got it working with some hacks. I'll clean it up and submit it as a patch today. I'm seriously digging your project!! :-)

**Comment by jacquescrocker** [comment]
Ok, got all the specs running. bundler sure helps! `bundle && bundle exec spec spec`

check out the commits at http://github.com/railsjedi/frank

Will keep improving upon it tonight

**Comment by jacquescrocker** [comment]
Woohoo!
http://github.com/railsjedi/frank/commit/b84a2097ad7cece22cfd8edd2fbe930004ba322c

Allows someone to create initializers.rb, and then they can just paste in a simple compass configuration script. Tested that its working awesome on my project!

**Comment by jacquescrocker** [comment]
Oops, missed a hack I had on my project. Here's a fixup commit
http://github.com/railsjedi/frank/commit/96648a5f971968e5c5f58319ae23677e47612238

Now its working proper, on a new project. To test it, just add this to your initializers.rb:

```
require 'compass'

Compass.configuration do |config|
  # project_path should be the directory to which the sass directory is relative.
  # I think maybe this should be one more directory up from the configuration file.
  # Please update this if it is or remove this message if it can stay the way it is.
  config.project_path = File.join(File.dirname(__FILE__), "..")
  config.sass_dir = File.join('dynamic', 'stylesheets')
end

# sass_engine_options returns a hash, you can merge it with other options.
Frank.sass_options = Compass.sass_engine_options
```

**Comment by jacquescrocker** [comment]
Fixed in http://github.com/blahed/frank/tree/0.4.x

No compass configuration needed anymore. If the compass gem is installed (via Gemfile, or rubygems), we'll automatically get it set up
