### ISSUE TITLE
relative urls?

### ISSUE THREAD

**Issue by revdan** [trvsdnn/frank#72]
Hi there,

I've been using Frank to put together a project and I love it so far. 

I've got folders nested as category/subcategory and I've written helpers/partials to handle the navigation which works great. 

While  testing the styles/images/js all work fine across the site, but when I export to a static site, it all just breaks as it's not generating relative urls. 

Any tips to get round this? The whole point of me doing it this way rather than just making a static site is that I don't have to individually edit every page...

Thanks in advance,
Dan

**Comment by trvsdnn** [comment]
Try exporting with --production

**Comment by revdan** [comment]
Doh! Thanks :)

I ended up writing a helper, but I'll bear this in mind.
