### ISSUE TITLE
Add -f option for export

### ISSUE THREAD

**Issue by Dahie** [trvsdnn/frank#74]
It would be cool to have an option `-f` or `--force` option in the `frank export` command. This would force to overwrite existing files and skip the manual prompt.

**Comment by trvsdnn** [comment]
It actually used to ask you if the folder happened to already exist. This will get added back, or a -f or something equivalent will be added.

**Comment by Dahie** [comment]
frank does ask at the moment in version 1.0.10, however there are many moments (es specially when included in automated scripts and cronjobs) where the manual prompt isn't helpful/required.

**Comment by trvsdnn** [comment]
Added this in 1.0.11. `frank export -f blah`
