### ISSUE TITLE
Get the directory of a 'view' from the 'layout'.

### ISSUE THREAD

**Issue by joesavage** [trvsdnn/frank#79]
I'm currently building my tutorial website with Frank, and it's going great so far however I've run into an issue. My directory structure consists of category folders (such as "category_one") inside of my "dynamic" folder, and then various ".erb" files for each tutorial inside each category folder. The problem is that each tutorial does not know what category it is in, and my layout for showing tutorials doesn't know the category of the tutorial it's dealing with either.

Is there any way of setting a default piece of YAML data for all files in a folder or passing the directory of a view file to the layout it's using? (Stored in the variable "dir" or something?)

At the moment I can't see any solution to this problem as the layout has no idea about the file it's doing the layout for, and hence I can't output the tutorial category in the generic tutorial show layout (all tutorial show pages should output their category along with other information)

Any information or advice on the issue would be appreciated.

Thanks,

Joe

**Comment by trvsdnn** [comment]
You should be able to use the `current_path` helper in your views/layouts to give you what you want... If I am understanding you correctly.

**Comment by joesavage** [comment]
`current_path` works a treat - thanks!
