### ISSUE TITLE
SCSS Support Busted

### ISSUE THREAD

**Issue by jacquescrocker** [trvsdnn/frank#8]
Looks like Tilt doesnt actually support scss. 

This patch seems to fix it though: 
http://gist.github.com/463200

**Comment by trvsdnn** [comment]
Yeah, i noticed this one before i released 0.3. I'll get some tests written and roll this into the next patch release.

**Comment by jacquescrocker** [comment]
Fixed via http://github.com/railsjedi/frank/commit/3328285ef2b4c1e79eb618dbc1e51275e4b8fe1e (tested on my project). I'll add some tests too

Did I fuck up the line encodings or something? I just saved it in textmate?

**Comment by jacquescrocker** [comment]
Oh. I have the strip linespace bundle :-). Here's a link to the bundle, I'd recommend it! 
http://cl.ly/17a3255694352a6265c3

**Comment by trvsdnn** [comment]
Thats a nice one, thanks.

**Comment by jacquescrocker** [comment]
Fixed in http://github.com/blahed/frank/tree/0.4.x
